#!/bin/sh -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/prerm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/prerm.mysql
    dbc_go php-cerebrate "$@"
fi

#DEBHELPER#
